# Generated by Django 5.0.4 on 2024-04-05 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_seller_user_pickuprequest_delete_buyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
